# -*- coding: utf-8 -*-
"""Exploratory Data Analysis using Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOO5ps6iBO4RZMrC4-MxiIfx4co2tWgn
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the Titanic dataset
df = sns.load_dataset('titanic')

# Basic exploration
print(df.info())
print(df.describe())

#Data Cleaning

df['age'] = df['age'].fillna(df['age'].median())
df.drop(columns=['deck'], inplace=True)

#Q1 :- Passenger Count by Gender

plt.figure(figsize=(6,4))
sns.countplot(x='sex', data=df, palette='Set2')
plt.title('Number of Passengers by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

#Q2 :- Passenger Count by Class

plt.figure(figsize=(6,4))
sns.countplot(x='pclass', data=df, palette='viridis')
plt.title('Number of Passengers in Each Class')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.show()

#Q3 :- Distribution of Passenger Age

plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=30, kde=True, color='blue')
plt.title('Distribution of Passenger Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#Q4 :- Fare Outlier Detection

plt.figure(figsize=(6,4))
sns.boxplot(x=df['fare'], color='salmon')
plt.title('Boxplot of Fare to Detect Outliers')
plt.xlabel('Fare')
plt.show()

#Q5 :- Scatterplots: Age, Fare, and Family Size

# a. Relationship between Age and Fare
plt.figure(figsize=(8,5))
sns.scatterplot(x='age', y='fare', data=df, alpha=0.5)
plt.title('Relationship between Age and Fare')
plt.show()

# b. Family Size (SibSp + Parch) and Fare
df['family_size'] = df['sibsp'] + df['parch']
plt.figure(figsize=(8,5))
sns.scatterplot(x='family_size', y='fare', data=df, color='green')
plt.title('Relationship between Family Size and Fare')
plt.show()

#Q6 :- Survival Count by Gender

plt.figure(figsize=(6,4))
sns.countplot(x='survived', hue='sex', data=df)
plt.title('Survival Count by Gender')
plt.legend(title='Gender', labels=['Male', 'Female'])
plt.show()

#Q7 :- Survival by Passenger Class

plt.figure(figsize=(6,4))
sns.barplot(x='pclass', y='survived', data=df, ci=None, palette='plasma')
plt.title('Survival Rate by Passenger Class')
plt.ylabel('Survival Rate')
plt.show()

#Q8 :- Correlation Heatmap

plt.figure(figsize=(10,6))
numeric_df = df.select_dtypes(include=['number'])
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Numerical Variables')
plt.show()

"""Q9 :- Highest Average Fare by Class

Answer :- By calculating the mean fare per class:

1st Class: ~$84.15

2nd Class: ~$20.66

3rd Class: ~$13.68


Result: Passenger Class 1 paid the highest fare on average.

Q10 :- Final 5 Insights

Answer :-

1.   Gender Bias in Survival: Female passengers had a significantly higher survival rate than males despite being the minority on the ship.
2.   Class Advantage: Social class was a major predictor of survival; 1st-class passengers were much more likely to survive than 3rd-class passengers.

3.   Economic Disparity: The fare distribution was highly unequal, with 1st-class passengers paying vastly more than those in 2nd or 3rd class.
4.   Demographic Profile: The Titanic was primarily populated by young adults (20-40 years old), with fewer elderly passengers and children.

5.   Family Structure: Most passengers traveled alone or in small groups; however, those with very large family sizes (6+) generally occupied the lower classes.
"""